---
version: "3"
services:
  certificate-bot:
    build: .
    volumes:
      - "./data:/app/data:rw"
    environment:
      - UID=1000
      - GID=1000
      - API_KEY=
    stdin_open: true
    tty: true
    restart: unless-stopped
