---

- name: tasks
  hosts: localhost
  vars:
    - apt_packages:
      - python3
      - python3-pip
      - python3-venv
    - pip3_packages:
      - sqlalchemy
      - dateparser
      - python-telegram-bot

  tasks:
  - name: Upgrade all packages to the latest version
    apt:
      update_cache: yes
      name: "*"
      state: latest

  - name: Remove useless packages from the cache
    apt:
      autoclean: yes

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: "Install packages defined in apt_packages"
    apt:
      name: "{{ item }}"
      state: latest
    loop: "{{ apt_packages }}"
    when: apt_packages|default([])|count > 0

  - name: Create directory /venvs if it does not exist
    file:
      path: /venvs
      state: directory
      mode: '0755'

  - name: Create the initial virtualenv
    command:
      cmd: "python3 -m venv /venvs/venv"
      creates: "/venvs/venv"

  - name: "Install python pip requirements defined in pip3_packages"
    pip:
      name: "{{ item }}"
      state: forcereinstall
      virtualenv: /venvs/venv
    loop: "{{ pip3_packages }}"
    when: pip3_packages|default([])|count > 0

  - name: 'collect files'
    find:
      paths: "/var/lib/apt/lists/"
      hidden: true
      recurse: true
    register: collected_files

  - name: 'collect directories'
    find:
      paths: "/var/lib/apt/lists/"
      hidden: true
      recurse: true
      file_type: directory
    register: collected_directories

  - name: remove collected files and directories
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: >
      {{
        collected_files.files
        + collected_directories.files
      }}
